Repository TalismanSociety/talisman, pull requests merged in 2023-11, with the labels that each got.

#1138 Refactor custom network forms
  apps/extension/src/ui/apps/dashboard/routes/Networks/NetworkPage.tsx
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/Ethereum/EvmNetworkForm.tsx
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/Ethereum/RemoveEvmNetworkButton.tsx
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/Ethereum/ResetEvmNetworkButton.tsx
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/Ethereum/helpers.ts
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/Ethereum/schema.ts
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/NetworkRpcsListField.tsx
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/SubNetworkForm.tsx
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/Substrate/AccountFormatDropdown.tsx
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/Substrate/Add.tsx
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/Substrate/Edit.tsx
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/Substrate/Form.tsx
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/Substrate/RemoveSubNetworkButton.tsx
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/Substrate/ResetSubNetworkButton.tsx
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/Substrate/SubNetworkRpcsListField.tsx
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/Substrate/helpers.ts
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/Substrate/index.ts
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/Substrate/schema.ts
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/Substrate/types.ts
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/getEvmNetworkFormSchema.ts
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/getSubNetworkFormSchema.ts
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/index.ts
  apps/extension/src/ui/domains/Settings/ManageNetworks/NetworkForm/useRegisterFieldWithDebouncedValidation.ts
  apps/extension/src/ui/hooks/useCoinGeckoTokenImageUrl.ts
Labels: bug

#1137 fix: workaround for devices with no wasm simd support
  .changeset/sweet-trains-pump.md
  apps/extension/src/core/background.ts
  packages/scale/package.json
  packages/scale/src/capi/crypto/hashers.ts
  packages/scale/src/capi/crypto/index.ts
  packages/scale/src/capi/crypto/ss58.ts
  packages/scale/src/capi/crypto/util/index.test.ts
  packages/scale/src/capi/crypto/util/index.ts
  packages/scale/src/capi/crypto/util/nosimd.ts
  packages/scale/src/capi/crypto/util/simd.ts
  yarn.lock
Labels: P1 - high, bug

#1155 feat: hide dust (small token balances)
  .changeset/chatty-hotels-invite.md
  apps/extension/src/core/domains/app/store.settings.ts
  apps/extension/src/ui/apps/dashboard/routes/Settings/GeneralPage.tsx
  apps/extension/src/ui/apps/dashboard/routes/Settings/NetworksTokensPage.tsx
  apps/extension/src/ui/domains/Portfolio/AssetsTable/usePortfolioSymbolBalances.ts
  packages/icons/src/icons/chain.svg
  packages/icons/src/icons/coins.svg
  packages/icons/src/index.ts
Labels: enhancement, quick-fix, shape-up
