Repository TalismanSociety/talisman, pull requests merged in 2025-05, with the labels that each got.

#1919 fix: download images from statically if githack fails
  apps/extension/src/ui/domains/Asset/AssetLogo.tsx
  apps/extension/src/ui/domains/Asset/ChainLogo.tsx
  apps/extension/src/ui/hooks/useGithubImageUrl.ts
Labels: QA pass

#1933 fix: asset discovery scanner mixing up balances
  packages/extension-core/src/domains/assetDiscovery/scanner.ts
Labels: bug, QA pass

#1930 fix: allow multiple substrate-tokens to have the same symbol
  .changeset/fresh-pets-whisper.md
  apps/extension/src/ui/util/isTransferableToken.ts
  apps/extension/tests/mocks/api.ts
  packages/balances/package.json
  packages/balances/src/modules/SubstrateTokensModule.ts
  packages/extension-core/src/domains/transactions/migrations/index.ts
  packages/extension-core/src/libs/migrations/index.ts
  pnpm-lock.yaml
Labels: bug

#1940 feat: improved formatPrice and cleanup signature
  .changeset/silly-llamas-fly.md
  packages/util/src/formatPrice.test.ts
  packages/util/src/formatPrice.ts
Labels: QA pass

#1965 feat: vs_currency tao in AssetPriceChart
  apps/extension/src/ui/domains/Asset/AssetPriceChart.tsx
Labels: enhancement

#1966 feat: change24h for vs_currency tao
  packages/token-rates/src/TokenRates.ts
Labels: enhancement

#1969 fix: never show NaN tao price
  .changeset/khaki-tables-vanish.md
  packages/token-rates/src/TokenRates.ts
Labels: bug

#1974 feat: bump polkadot in copy address format picker
  apps/extension/src/ui/domains/CopyAddress/CopyAddressChainForm.tsx
Labels: QA pass

#1973 feat: monad animation on token details page
  apps/extension/src/ui/domains/Portfolio/AssetDetails/PopupAssetDetails.tsx
  apps/extension/src/ui/domains/Portfolio/AssetDetails/animations/monad/MonadAnimation.tsx
  apps/extension/src/ui/domains/Portfolio/AssetDetails/animations/monad/monad-animated-1.gif
  apps/extension/src/ui/domains/Portfolio/AssetDetails/animations/monad/monad-animated-2.gif
Labels: QA pass

#1987 chore: update btn size
  apps/extension/src/ui/domains/Staking/Bittensor/BittensorBondModal/Drawers/BittensorSelectStakeDrawer.tsx
Labels: QA pass
